package dev.jessefu.component_base.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import dev.jessefu.component_base.db.entity.AccountEntity;
import dev.jessefu.component_base.db.entity.CategoryEntity;

import dev.jessefu.component_base.db.AccountEntityDao;
import dev.jessefu.component_base.db.CategoryEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig accountEntityDaoConfig;
    private final DaoConfig categoryEntityDaoConfig;

    private final AccountEntityDao accountEntityDao;
    private final CategoryEntityDao categoryEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        accountEntityDaoConfig = daoConfigMap.get(AccountEntityDao.class).clone();
        accountEntityDaoConfig.initIdentityScope(type);

        categoryEntityDaoConfig = daoConfigMap.get(CategoryEntityDao.class).clone();
        categoryEntityDaoConfig.initIdentityScope(type);

        accountEntityDao = new AccountEntityDao(accountEntityDaoConfig, this);
        categoryEntityDao = new CategoryEntityDao(categoryEntityDaoConfig, this);

        registerDao(AccountEntity.class, accountEntityDao);
        registerDao(CategoryEntity.class, categoryEntityDao);
    }
    
    public void clear() {
        accountEntityDaoConfig.clearIdentityScope();
        categoryEntityDaoConfig.clearIdentityScope();
    }

    public AccountEntityDao getAccountEntityDao() {
        return accountEntityDao;
    }

    public CategoryEntityDao getCategoryEntityDao() {
        return categoryEntityDao;
    }

}
